### ISSUE TITLE
Support for Admonition and other markdown-it plugins

### ISSUE THREAD

**Issue by Stanzilla** [remarkjs/remark-frontmatter#11]
### Subject of the feature

I would love to get support for [Admonition](https://squidfunk.github.io/mkdocs-material/extensions/admonition/) and other PyMarkdown extensions

### Problem

Currently they are all detected as errors and/or formatted away

### Expected behaviour

Should be able to use them without error

### Alternatives

What are the alternative solutions?  Please describe what else you have considered?

**Comment by wooorm** [comment]
Hi there! 👋

- Is there a reason you posted this in remark-frontmatter?
- with remark you can make most any plugin you want, yourself, here's a short section on that: https://github.com/remarkjs/remark/blob/master/doc/plugins.md#creating-plugins, and here a guide https://unifiedjs.com/learn/guide/create-a-plugin/
- the syntax of admonition looks interesting! I'm not sure about the whitespace before lines. It's also somewhat similar to generic extensions https://unifiedjs.com/explore/package/remark-generic-extensions/

**Comment by Stanzilla** [comment]
Mostly because I was really unsure in which part of remark this belongs and thought frontmatter made the most sense this is a start block. Sadly I probably won't have time to make my own extension.

**Comment by wooorm** [comment]
I don't either. But you could open an issue in the ideas repo, that's a good place for this, maybe someone'll pick up on it there!
