### ISSUE TITLE
Frontmatter being linted as regular Markdown in 3.0

### ISSUE THREAD

**Issue by nschonni** [remarkjs/remark-frontmatter#14]
### Subject of the issue

Saw the note and realize this is related to the parser change, but I think some of these are bugs in the new parser. 
If you want me to open separate ones upstream, let me know.

Here is an example of a previously passing repo hitting almost 2K issues with the latest:

https://github.com/nodejs/nodejs.org/pull/3434/checks?check_run_id=1209164695

- flagging the closing of an frontmatter section as a bad ATX heading
- flagging the last line in in the fronmatter as a heading with invalid indenting
- flagging lists in frontmatter as requiring asterisks. This might be OK, as it was also the enforced style in the document, but previously didn't enforce it in frontmatter lists. Not sure if this is good as Yaml frontmatter thoguh
- flagging indented Yaml lines as indent code blocks

### Your environment

*   **OS**: 
*   **Packages**: 
*   **Env**: 

### Steps to reproduce

Sorry, it's not a minimal reproduction, but I could try and trim something down to just a single file with frontmatter and the ruleset
https://github.com/nodejs/nodejs.org

### Expected behavior

Frontmatter should still be treated as Yaml

### Actual behavior

Frontmatter is being linted as plain Markdown content

**Comment by wooorm** [comment]
This sounds like you're using the new plugin but *not* on the new beta of remark?

**Comment by wooorm** [comment]
I’m pretty sure dependabot just updated this plugin, but not to the beta of remark. In this case, the release notes are clear:

> fb1357b Update for micromark in remark@13 (breaking, this update will not work for remark lower than v13)

and the results you see are that: it doesn’t work on remark 12.

**Comment by nschonni** [comment]
Correct, looking at the package.json it only has the remark bump as a devDependency. Should that also be a peerDependency if you want to enforce them going together? Although I'm not really sure what the current support for peerDependency is

**Comment by wooorm** [comment]
This change is breaking because on *your* side, you also need to update remark-cli.

There is some form of peer dependencies indeed, however, I have bad experience with `peerDependencies`, hence I do it in documentation. E.g., in this case you’re using remark-cli and this plugin does not need remark-cli, or remark even, to work.

**Comment by wooorm** [comment]
Closed by https://github.com/remarkjs/remark/releases/tag/13.0.0
