### ISSUE TITLE
The docs example doesn't work

### ISSUE THREAD

**Issue by kentcdodds** [remarkjs/remark-frontmatter#16]
Because ESM mostly. I tried updating it to this:

```js
import {toVFile} from 'to-vfile'
import {reporter} from 'vfile-reporter'
import unified from 'unified'
import parse from 'remark-parse'
import stringify from 'remark-stringify'
import frontmatter from 'remark-frontmatter'

unified()
  .use(parse)
  .use(stringify)
  .use(frontmatter, ['yaml', 'toml'])
  .use(logger)
  .process(toVFile('example.md'), function (err, file) {
    console.error(reporter(err || file))
    console.log(String(file))
  })

function logger() {
  return console.dir
}
```

However, the output I get for this is:

```
{
  type: 'root',
  children: [],
  position: {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 1, column: 1, offset: 0 }
  }
}
example.md: no issues found
```

This is what's brought me to the example in the first place. I can't figure out how to get this plugin to parse the frontmatter. I'm trying to update frontmatter in my blog posts and I'm unable to get the frontmatter parsed so my custom visitor can modify it.

**Comment by wooorm** [comment]
Downgrade `to-vfile` for now, that should solve it.

An internal property changed between the two versions (unified et all are still on the old, you’re using the new).

I’ll have to think of a warning or so to make this obvious instead of a silent failure 🤔

**Comment by wooorm** [comment]
@ChristianMurphy Thoughts on how to best solve this?

Here are some of my ideas:

- Publish a new `vfile` that `contents` shouldn’t be used
- Add a getter/setter on the old vfile for `contents` that uses `value` instead
- Publish current unified that either uses `value` or `contents` depending on which one is set

(with the assumption that it’d take another month to release everything and stabilize the whole ecosystem again)

**Comment by wooorm** [comment]
OK I'll try the unified 'value' one. That seems best. And we can go from there

**Comment by wooorm** [comment]
Note: the example also include `vfile.readSync`, to read the file. So `toVFile('example.md')` should be `toVFile.readSync('example.md')` in this reproduction. With that, plus the linked PR, I think it works.

**Comment by wooorm** [comment]
Fixed!
