### ISSUE TITLE
Remark-Frontmatter does not generate a yaml node

### ISSUE THREAD

**Issue by Tiim** [remarkjs/remark-frontmatter#18]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

4.0.1

### Link to runnable example

https://codesandbox.io/s/remark-frontmatter-bug-ui725e?file=/src/index.js

### Steps to reproduce

Take a look at the codesandbox.
This seems to happen in node, as well as in the browser.

### Expected behavior

The remark-frontmatter plugin should convert the frontmatter into a 'yaml' block. In the runnable example the first AST node of the root node should be a node of type 'yaml' with the content of the frontmatter inside.

### Actual behavior

It seems like the frontmatter plugin does not do anything.

This may be a similar problem as #16. Although the problem persists when not using a v-file at all (as shown in the codesandbox).

### Runtime

Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment]
This is as expected.
`remark-frontmatter` expects the frontmatter to be at the start of the document, you put some content before the frontmatter.
Removing the content before, for example https://codesandbox.io/s/remark-frontmatter-bug-forked-ln8c14?file=/src/index.js parses as expected.
If you want it to be picked up anywhere in the document, you can use the `anywhere` option https://github.com/remarkjs/remark-frontmatter#matter

**Comment by Tiim** [comment]
Thanks for the quick answer, so just to clarify: A newline counts as content?

**Comment by wooorm** [comment]
Yes, frontmatter does not parse if there is whitespace before it. The reason is that GH handles frontmatter that way, too.
