### ISSUE TITLE
Support custom language annotations

### ISSUE THREAD

**Issue by remcohaszing** [remarkjs/remark-frontmatter#20]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Some markdown processors support language tags for frontmatter, similar to code blocks.

```markdown
---
description: this is yaml
---
```

```markdown
+++
description = "this is toml"
+++
```

```markdown
---json
{
  "description": "this is json"
}
---
```

Prettier supports this. In an effort to update all remark related code / dependencies in Prettier, I would love for `remark-frontmatter` to support this.

### Solution

The solution seems simple: Add support for language annotations.

However, this doesn’t align with the AST node format. Currently the type of the node is the language of the node, so `{"type": "yaml"}` or `{"type": "toml"}` nodes are produced to represent YAML or TOML frontmatter data respectively. This would be problematic for example for the following markdown:

```markdown
---heading
Some arbritrary text
---

# A title
```

This would make the frontmatter data indistinguishable from headings.

To tackle this problem, I suggest to change the type of frontmatter nodes to `frontmatter` The frontmatter node will have a `lang` property, just like `code` nodes. This means the above document will be represented as:

```js
{
  type: root
  children: [
    {
      type: 'frontmatter',
      lang: 'heading',
      value: 'Some arbritrary text'
    }
    {
      type: 'heading',
      depth: 1
      children: [ /* … */ ]
    },
  ]
}
```

This is definitely a breaking change.

### Alternatives

I’m not sure.

**Comment by wooorm** [comment]
1. I am typically quite strongly against extending markdown in ways that break most parsers and are unspecified. Why would you use a language that has a standard and then add things to it that break everywhere? 🤷‍♂️ There’s a good reason that TypeScript doesn’t extend JavaScript like that anymore. It’s a gradient of course between what’s extremely common in practise (YAML frontmatter itself) and things like this. But with YAML frontmatter we can follow an extremely common implementation: GitHub.
2. Prettier has done some weird custom things in the past, and later removed them. Perhaps that’s possible.
3. At this point, mdast is used in lots and lots of places across programming languages. Replacing nodes has happened a few times 10 years ago when it was all really small back then, but it was still a lot of work and resulted in crashes for people using packages on different versions.

> However, this doesn’t align with the AST node format.

You can always add data fields for your custom needs.

> This would make the frontmatter data indistinguishable from headings.

I don’t understand what the AST has to do with that code example.
```json
{"type":"yaml","data":{"lang":"json"},"value":"Some arbritrary text"}
```
^-- is different from a heading?

**Comment by ChristianMurphy** [comment]
I'd agree with @wooorm's points.
And also add that beyond presets, custom marker and types could be added as well.

I'd also note from your example that valid JSON is also valid yaml 🙂 

For the `lang` property idea, do you have a use case in mind where it would need something beyond a preset known list of languages?
Will you somehow be dynamically adding languages on the fly?

**Comment by j-f1** [comment]
A real-world example of this syntax is Eleventy, which [uses `gray-matter` and therefore supports YAML, JSON, and JS](https://www.11ty.dev/docs/data-frontmatter/#alternative-front-matter-formats), and is extensible to arbitrary custom formats. For example:

```js
---js
{
  title: "My page title",
  currentDate: function() {
    // You can have a JavaScript function here!
    return (new Date()).toLocaleString();
  }
}
---
```

I think there’s a way forward that avoids using `remark-frontmatter` inside of Prettier (since we already have a frontmatter parser that we also use for HTML and CSS. This still could be a useful addition to the package for other clients, though.

> 1. I am typically quite strongly against extending markdown in ways that break most parsers and are unspecified. […]

While I agree that this is typically a bad idea, I think that practically Prettier shouldn’t break people’s code even if they make bad decisions. So we’re incentivized to add support for a bunch of syntax extensions (especially where the syntax they employ is unlikely to be used with different whitespace expectations elsewhere) so we can at least try to guarantee users’ code won’t be broken when formatting.

**Comment by remcohaszing** [comment]
> 1. I am typically quite strongly against extending markdown in ways that break most parsers and are unspecified. Why would you use a language that has a standard and then add things to it that break everywhere? man_shrugging There’s a good reason that TypeScript doesn’t extend JavaScript like that anymore. It’s a gradient of course between what’s extremely common in practise (YAML frontmatter itself) and things like this. But with YAML frontmatter we can follow an extremely common implementation: GitHub.

I feel the same way. I’m only proposing this because I found out Prettier supports it, and I get it from a formatter perspective. I personally wouldn’t recommend anyone to use it.

---

> I'd also note from your example that valid JSON is also valid yaml :slightly_smiling_face:

That’s true, perhaps I should have used XML as an example. :smile: 

---

Based on https://github.com/prettier/prettier/issues/12209#issuecomment-1283847595. I no longer see the need for this, so I’m closing this issue.

**Comment by wooorm** [comment]
> I think that practically Prettier shouldn’t break people’s code even if they make bad decisions. So we’re incentivized to add support for a bunch of syntax extensions (especially where the syntax they employ is unlikely to be used with different whitespace expectations elsewhere) so we can at least try to guarantee users’ code won’t be broken when formatting.

I think this will be a footgun: markdown (and HTML) are *lax* languages which allow *any* character. Choosing to format them in a way that strays from the spec (HTML spec, CM/GFM), will result in markdown which was written for that spec, to be broken.

Take for example math. Someone adhering to CommonMark could write: `Lorem ipsum somewhere between $123,- &amp; $456,-`. If Prettier decides to support math, it has to interpret that character reference as literal characters and keep it in while being useless. If Prettier decides to follow CM/GFM, it can format the document and use a pretty `&`.
It’s a small, pretty useless example, but I think it shows the problem.

Particularly the rules around how to parse markdown and HTML and super complex.
I can understand supporting some custom extensions to simpler languages (e.g., CSS), or pretty strong languages (e.g., JS). But even then you’ll run into some differences: in TypeScript, some things are seen as types normally, but when JSX is enabled, as JSX.

---

Ok, good that this isn’t needed anymore and there is a workaround for Prettier.
For future readers stumbling on this: [I still have a few open questions above](https://github.com/remarkjs/remark-frontmatter/issues/20#issuecomment-1282466016) that I’d like an answer on.
