### ISSUE TITLE
linting the contents of frontmatter

### ISSUE THREAD

**Issue by kachkaev** [remarkjs/remark-frontmatter#4]
After adding `remark-frontmatter` to `.remarkrc` I finally stopped seeing strange remark-lint errors. The most common one was saying _Code blocks should be fenced_ and was triggered because the parser treated padded yaml lines as normal markdown:

```yaml
---
parent:
  hello:
    - world # <--   Code blocks should be fenced
---
```

Now, when `remark-frontmatter` is installed, I seem to never see errors or warnings produced by remark-lint again, even when yaml is intentionally broken:

```yaml
---
parent:
  hello
    world
---
```

Given that the contents of frontmatter are being parsed anyway, would it be possible to add simple linting to it? It could just say _Frontmatter contents cannot be parsed because of syntax problems_ without pointing to a specific yaml/toml line, and that would be amazing already!

**Comment by wooorm** [comment]
remark-frontmatter just parses and stringifies frontmatter, it doesn’t actually check if it’s parsable.
Sounds like you need some custom plugin to actually parse the frontmatter, potentially setting it on the `vfile`?

Related: [`landakram/remark-parse-yaml`](https://github.com/landakram/remark-parse-yaml) and [`remarkjs/remark-yaml-config`](https://github.com/remarkjs/remark-yaml-config).

**Comment by kachkaev** [comment]
I'll try to find a solution and will contribute back if I do. To be honest, my main concern in this issue is not whether frontmatter is being parsed or not. The warning is a sing of that the FM contents can be treated like padded code blocks, which suggests an problem with parsing order.

**Comment by wooorm** [comment]
This seems to be the exact same error as reported on remark-lint, https://github.com/remarkjs/remark-lint/issues/169. Let’s discuss there!
