### ISSUE TITLE
only parses 1 key value pair

### ISSUE THREAD

**Issue by episodeyang** [remarkjs/remark-frontmatter#5]
given this markdown:

```markdown
---
author: "Ge Yang"
some: "value"
---
# KL Divergence and Something

Let's test the handling of lists
- this is an item
- this is another one.

Here is a paragraph $\alpha$ and some$$
\alpha + \beta \text{math}
$$

And some more text
\`\`\`python
print('hey')
\`\`\`

And some table

| some title | data field |
|:----------:|:----------:|
| entry 1    | value of 1 |
```

the AST returned by the following setup only gives the `author: Ge Yang` field, but not the `some: "value"`. 

Is this expected?

```javascript
// import remark from "remark";
import unified from "unified";
import remarkParse from "remark-parse";
import frontMatter from "remark-frontmatter";

const parser = unified()
    .use(remarkParse)
    .use(frontMatter, ['yaml']);

export const parse = parser.parse;
```

**Comment by episodeyang** [comment]
I think it was my WebStorm that is messed up. The file wasn't saved. WebStorm has silently crashed (just not saving files) but other wise functional. This is the second time this happens. 

The newest version of WebStorm is quite buggy.

**Comment by episodeyang** [comment]
Turned out that this is a problem with the `babel-plugin-inline-import`. It does not load the new version of the file.

**Comment by wooorm** [comment]
Hmm, weird. Anyway, unrelated to remark! But good luck on your project!

**Comment by episodeyang** [comment]
Thanks! and thanks for all the remark work!
