### ISSUE TITLE
Parse multiple frontmatter section in a text

### ISSUE THREAD

**Issue by florent-andre** [remarkjs/remark-frontmatter#9]
### Subject of the feature

It could be interesting to have multiple frontmatter sections in a md and get them parsed (if it's allowed in the specs)

### Problem

* Considering this md : 
``` markdown
---
frontMatter1:
    firstValue
---
# A paragraph example
and a text


---
frontMatter2:
	secondValue
---
# A new paragraph example
good to know
```

* I only got the first section transformed to a `yaml` node. The second one is only defined by two `thematicBreak`

Is this intended ? Can it be configured in a way or another ?

**Comment by wooorm** [comment]
Hi there! This is intended. There is no spec for YAML frontmatter, but how YAML and YAML in Markdown is typically supported, is only at the top of the document, and only once.

It’s possible to create a plugin that supports things like this though!
